[package]
name = "gfxfilemanager"
version = "0.2.0"
authors = ["Lukas Wirth <lukastw97@gmail.com>"]
edition = "2021"

[dependencies]
winapi = {version =  "0.3.9", features = ["ntdef","windef","minwindef","minwinbase"]}
